---
- hosts: 3d_print_pis
  tasks:

  - name: read variables from main_conf
    include_vars:
      file: conf/main_conf.yml
      name: main

  - name: Update all packages to their latest version
    apt:
      name: "*"
      state: latest
    become: yes

  - name: install kiauh
    import_tasks: install_kiauh.yml
    when: main.KIAUH == true

  - name: install mjpg-streamer
    import_tasks: install_mjpg-streamer.yml
    when: main.KIAUH == true

  - name: get klipper dependencies
    import_tasks: dependencies/klipper.yml
      
  - name: installing klipper
    import_tasks: install_klipper.yml
    
  - name: get moonraker dependencies
    import_tasks: dependencies/moonraker.yml
    
  - name: installing moonraker
    import_tasks: install_moonraker.yml
      
  - name: get mainsail dependencies
    import_tasks: dependencies/mainsail.yml
    
  - name: installing mainsail
    import_tasks: install_mainsail.yml
